#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'
dotnet format
dotnet build 
dotnet list ./Ayudantia/Ayudantia.csproj package --outdated

dotnet ef migrations script --project ./Ayudantia/Ayudantia.csproj --startup-project ./Ayudantia/Ayudantia.csproj



